package com.example.dietsoft.dietfood_backend.entities.enums;

public enum CategoriaAlimentos {
    CARBOIDRATOS,
    PROTEINAS,
    GORDURAS,
    LATICINIOS,
    VEGETAIS,
    FRUTAS,
    LEGUMINOSAS,
    OLEAGINOSAS,
    DOCES_E_SOBREMESAS,
    BEBIDAS,
    GRAOS_E_CEREAIS,
    PROCESSADOS_E_INDUSTRIALIZADOS,
    SUPLEMENTOS,
    CONDIMENTOS_E_TEMPEROS,
    SNACKS_E_PETISCOS,
    FIBRAS,
    VITAMINAS_MINERAIS,
    ANTIOXIDANTES,



}
